// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewacimboqwsmzwvkazsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YWNpbWJvcXdzbXp3dmthenN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzQ3NzQsImV4cCI6MjA3MTg1MDc3NH0.YUJ-bXkl7SrKeDyqLxOdNXDvaNEY2jYO0x6sknRtpIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});